### ISSUE TITLE
”Issueベースの開発”  レビュー依頼

### ISSUE THREAD

**Issue by Arther1201** [Arther1201/app#14]
###  実装予定の機能
- [x]  患者名検索機能
- [x]  カルテ番号検索機能
- [x]  補綴種類検索機能
- [x]  日付検索機能
- [x]  画像の添付機能
- [x]  納品チェック機能
- [ ]  チャット機能
- [x]  カルテメモ機能
- [x]  お薬手帳記載機能

###  必要なページ
- [x]  トップページ
- [x]  ログインページ
- [x]  新規登録ページ
- [x]  メールアドレス・パスワード変更ページ
- [x]  患者一覧
- [x]  各検索結果ページ
- [ ]  チャット画面
- [x]  患者詳細画面

**Comment by kashiwagi-rena** [comment]
ご提出ありがとうございます。
現在issueには、viewしかのっていないように思います。
機能面もissueに記載していただいた方が漏れが出ずに良いと思うため、追記をお願いいたします。

**Comment by Arther1201** [comment]
すみません。間違えて再レビューを押してしまいました。
再度修正いたします。

**Comment by Arther1201** [comment]
修正いたしました！
ご指摘の機能面について合っていますでしょうか？
お手数ですが再度レビューをお願いいたします！

**Comment by tmtkzk0823** [comment]
修正ありがとうございます。
以下、コメントになります。

---

> ご指摘の機能面について合っていますでしょうか？

認識は合っていると思います。ですが、少々1つのissueが大きくなってしまったので、より細分化できないか再度確認してみましょう。
（例：ログイン機能を作成する際は、ログイン画面の作成とログインの機能（ロジック）を作成するissueは分けるなど）

---
- デプロイ、rails newなどのカードも作成しましょう。
- 外部APIや技術に関して調査するものがあれば、それもカードを用意しましょう。
---

上記の観点も踏まえて再度、ご確認をお願いします。

**Comment by Arther1201** [comment]
レビューありがとうございます！
そしてご指摘いただき本当にありがとうございます！
issueの細分化してみました！っといってもviewと機能を分割したという感じですが
あとデプロイとRailsプロジェクトの初期設定を追加いたしました！
外部APIの技術ですが今回のアプリに関してはあまり必要ないかと思いました！
追加で機能を追加する際は技術を調査しようと思います！
お手数ですが再度レビューをお願いいたします！

**Comment by Tsuchiya2** [comment]
<img width="757" alt="image" src="https://github.com/user-attachments/assets/bd0206ca-ba76-464b-8555-838e6e6f3c79">

すみません。看板・issue・ストーリーポイントが確認できなかったので確認をお願いできますでしょうか。

**Comment by Arther1201** [comment]
レビューありがとうございます！
プロジェクトをリンクするにしたのですがこれで見れますでしょうか？
お忙しい中申し訳ございません
再度ご確認いただけると幸いです。
よろしくお願いいたします！

**Comment by tmtkzk0823** [comment]
修正ありがとうございます。
- ログイン機能のissueはあるのですが、ログアウト機能のissueが見受けられませんでした。
ログアウト機能を実装予定でしたらissueの追加をお願いします。

**Comment by Arther1201** [comment]
レビューありがとうございます！
確かに、おっしゃる通りログアウトのタスクを失念しておりました
ご指摘いただきありがとうございます！大変助かります！
ログアウトのissueを追加いたしました！
お忙しいとは思いますが再度レビューをしていただけると幸いです！
よろしくお願いいたします！

**Comment by kenchasonakai** [comment]
LGTMです！
